module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  allowed_formats: 0
  automated_cron: 0
  bene_core: 0
  bene_event: 0
  bene_hero_block: 0
  bene_listing_page: 0
  bene_media: 0
  bene_media_file: 0
  bene_media_video: 0
  bene_migrate_google_sheets: 0
  bene_news: 0
  bene_page: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_rewrite: 0
  config_update: 0
  contact: 0
  contact_storage: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  email_registration: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  features: 0
  features_ui: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  link: 0
  linkit: 0
  media: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_google_sheets: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  picture_background_formatter: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  bene: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bene_parent: 0
  bene_child: 0
  art_test: 0
profile: bene
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
